
[workspace]
resolver = '2'
members = [
	'bundler-packages/resolutions-rs',
	'bundler-packages/runtime-rs',
	'bundler-packages/solc-rs',
	'bundler-packages/bundler-rs',
	'app/src-tauri',
	'packages/revm',
]

[profile.release]
lto = true
