
[workspace]
resolver = '2'
members = [
	'bundler-packages/resolutions-rs',
	'bundler-packages/runtime-rs',
	'bundler-packages/solc-rs',
	'bundler-packages/bundler-rs',
	'apps/app/src-tauri',
]

[profile.release]
lto = true
