on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: Lint

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Run Linters
        run: pnpm nx affected --targets=lint:check
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Run Formatters
        run: pnpm nx affected --targets=format:check
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Run Package.json formatter - Run `pnpm sort-package-json` to fix
        run: pnpm sort-package-json:check
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
